version: "3"

networks:
  rest-api:

services:

  rest-api:
    environment:
      - HTTP_ADDR=:8080
      - LOG_LEVEL=debug
      - CONFIG_PATH=/go/src/app/config/config.yml
    build: ./
    command: "./user-segmentation-service"
    ports:
      - 8080:8080
    depends_on:
      - postgres
    networks:
      - rest-api


  postgres:
    restart: always
    image: postgres:latest
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=segmentation
    networks:
      - rest-api