version: "3"

networks:
  rest-api:

services:

  rest-api:
    restart: on-failure
    environment:
      - HTTP_ADDR=:8080
      - LOG_LEVEL=debug
      - PG_URL=postgres://postgres:qwerty@postgres:5432/segmentation?sslmode=disable
      - CONFIG_PATH=/go/src/server/config/config.yml
    build: ./
    command: >
      /bin/sh -c "
        migrate -path ./migrations -database 'postgres://postgres:qwerty@postgres:5432/segmentation?sslmode=disable' up &&
        ./user-segmentation-service
      "
    ports:
      - 8080:8080
    depends_on:
      - postgres
    networks:
      - rest-api


  postgres:
    restart: always
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=segmentation
    networks:
      - rest-api